trigger:
- main

pool:
  name: demovmpool

steps:

- script: | 
    sudo apt update
    sudo apt install docker.io -y
    sudo systemctl start docker

- script: |
    echo "Current user: $(whoami)"
    sudo usermod -aG docker $(whoami)
    sudo chmod 666 /var/run/docker.sock
  displayName: 'Grant permissions to /var/run/docker.sock'

- script: |
    docker ps
  displayName: 'Verify Docker access'
  
- task: Docker@2
  inputs:
    containerRegistry: 'devocontainerregistry'
    repository: 'demoimage'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
